# Generated by Django 3.2.9 on 2021-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text", "0002_auto_20211205_2253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
